# Configuration des APIs de Paiement PHARMAX

# --- FLOUCI ---
# Remplacez par vos clés réelles
flouci.app_token=VOTRE_PUBLIC_APP_TOKEN
flouci.app_secret=VOTRE_APP_SECRET

# --- STRIPE ---
# Remplacez par votre clé secrète (sk_test_...)
stripe.secret_key=sk_test_VOTRE_CLE_STRIPE
